repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0 # Use the ref you want to point at
  hooks:
  - id: check-merge-conflict
  - id: check-yaml
    exclude: "tests/data/yaml/bad_simple.yaml"
  - id: no-commit-to-branch
    args: [--branch, develop, --branch, main]
- repo: https://github.com/google/yapf
  rev: v0.40.2
  hooks:
  - id: yapf
    args: [--in-place, --recursive]
    stages: [commit]
    additional_dependencies: [toml]
- repo: https://github.com/PyCQA/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    args: [--extend-ignore, "P1,C812,C813,C814,C815,C816,W503,W605,B017,B028"]
    additional_dependencies: [flake8-2020, flake8-broken-line, flake8-bugbear, flake8-builtins, flake8-commas, flake8-comprehensions, flake8-docstrings, flake8-eradicate, flake8-import-order, flake8-mutable, flake8-pep3101, flake8-print, flake8-quotes, flake8-string-format, flake8-use-fstring, pep8-naming]
    stages: [commit]
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.17
  hooks:
  - id: mdformat
    exclude: "CHANGELOG.md"
    additional_dependencies:
    - mdformat-tables
    - mdformat-config
    - mdformat-frontmatter
    - mdformat-gfm
